# This section declares settings for the server.
[server]
host = "127.0.0.1"      # server host
port = 8080             # server port

# This section declares setting for the database.
[database]
file = "~/.gorse/temp/database.db"  # database file

# This section declares settings for recommendation.
[recommend]
model = "svd"           # recommendation model
similarity = "pearson"  # similarity metric for neighbors
cache_size = 100        # the number of cached recommendations
update_threshold = 10   # update model when more than 10 ratings are added
check_period = 1        # check for update every one minute

# This section declares hyperparameters for the recommendation model.
[params]
lr = 0.05               # learning rate
reg = 0.01              # regularization strength
n_epochs = 100          # number of epochs
n_factors = 10          # number of factors
random_state = 21       # random state (seed)
use_bias = false        # use bias
init_mean = 0.0         # mean of gaussian initial parameter
init_std = 0.001        # standard deviation of gaussian initial parameter
init_low = 0.0          # lower bound of uniform initial parameter
init_high = 1.0         # upper bound of uniform initial parameter
n_user_clusters = 10    # number of user cluster
n_item_clusters = 10    # number of item cluster
type = "baseline"       # type for KNN
user_based = true       # user based if true. otherwise item based.
similarity = "pearson"  # similarity metrics
k = 100                 # number of neighbors
min_k = 5               # least number of neighbors
optimizer = "bpr"       # optimizer for optimization (SGD/ALS/BPR)
shrinkage = 50          # shrinkage strength of similarity
alpha = 1.0             # alpha value, depend on context